language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    #- $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    #- SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
      # Test latest stable features
    - php: 8.1
      env: PHPSTAN=true COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

  allow_failures:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 8.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if [[ $COMPOSER1 = true ]]; then composer selfupdate --1; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  # simple-phpunit is the PHPUnit wrapper provided by the PHPUnit Bridge component and
  # it helps with testing legacy code and deprecations (composer require symfony/phpunit-bridge)
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
  - if [[ $PHPSTAN == true ]]; then composer phpstan; fi
  #- ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  # Let's test without the security bundle
  - if [[ $TESTNOSECURITYBUNDLE == true ]]; then composer remove --dev symfony/security-bundle && ./vendor/bin/simple-phpunit tests/NoSecurityBundleTest.php; fi

after_script:
  - ./vendor/bin/php-coveralls -v
